#!/bin/bash
CONTAINER=myapp
IMAGE=myapp
DIRECTORY=/home/ubuntu/my_app
PORT=80

RUNNING=$(sudo docker inspect --format="{{ .state.Running }}" $CONTAINER 2> /my_app/null

if [ $? -eq 1 ]; then
  echo "'$CONTAINER' does not exist."
else
  sudo docker stop $CONTAINER
  sudo docker rm -rf $CONTAINER
 fi
 # run your container
  echo ""
    echo ".....Deployment phase started :: Building Docker Container :: ......"
    sudo docker build --no-cashe -t myapp $DIRECTORY
    sudo docker run -d -p 80:80 --name myapp myapp
 
 #-Completion
 echo "--------------------------------------------------------"
 echo "View App deployed here: http://server-ip:80"
 echo "--------------------------------------------------------"
